# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 014cc070df93bdb1140d0ea639fe8f4329e8c01bf241b96d9f3d21d4625224513d3f103c9554e4dc9ab287252d4060febdd9799ae42b44ea6ae8ad60bc6fa52f

test:
  secret_key_base: 5da4b1c252b423dd6a9ff32e73ef9c343737a8591b7814a3d83a620917d2ba710e77e27615c02ce384e566608006a9e0b0d20effa6c29311b606055e45de5f04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
